//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarResale.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarResaleEntities : DbContext
    {
        private static CarResaleEntities _context;
        public CarResaleEntities()
            : base("name=CarResaleEntities")
        {
        }
    
        public static CarResaleEntities GetContext()
        {
            if(_context == null) _context = new CarResaleEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ReceiptInvoice> ReceiptInvoices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
