//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarResale.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReceiptInvoice
    {
        public int ID { get; set; }
        public System.DateTime Date_of_acquisition { get; set; }
        public decimal Acquisistion_price { get; set; }
        public Nullable<decimal> Other_costs { get; set; }
        public decimal Total_acquisistion_price { get; set; }
    }
}
