USE CarResale
GO

INSERT INTO Marks VALUES
	('Abarth'),
	('AC'),
	('Acura'),
	('Aeolus'),
	('Aiways'),
	('Aito'),
	('Aixam'),
	('Alfa Romeo'),
	('Almac'),
	('Alpina'),
	('Alpine'),
	('Alternative Cars'),
	('AM General'),
	('Anteros'),
	('Apex'),
	('Apollo'),
	('Aptera'),
	('Arash'),
	('Arcimoto'), 
	('Arcfox'),
	('Ariel'),
	('Arrinera'), 
	('Artega'),
	('Aspid'),
	('Aston Martin'),
	('Audi'),
	('BAIC'),
	('Bajaj'),
	('Baojun'),
	('BAW'),
	('Bentley'),
	('Bestune'),
	('BMW'),
	('Bollore'), 
	('Bolwell'),
	('BAC'),
	('Brilliance'),
	('Buddy'),
	('Bufori'),
	('Bugatti'),
	('Buick'),
	('BYD'),
	('Cadillac'),
	('Callaway'),
	('Carver'),
	('Caterham'),
	('Chamonix'),
	('Changan'),
	('Changfeng'),
	('Changhe'),
	('Chery'),
	('Chevrolet'), 
	('Chrysler'),
	('Citroen'),
	('Ciwei'),
	('CUPRA'),
	('Czinger'),
	('Dacia'),
	('Daihatsu'), 
	('David Brown'), 
	('Dax'),
	('De la Chapelle'),
	('De Tomaso'), 
	('DeLorean'), 
	('Denza'), 
	('Detroit Electric'), 
	('Dodge'), 
	('Dongfeng'), 
	('Donkervoort'), 
	('DR'), 
	('DS'),  
	('Dynasty'),
	('Electric Raceabout'), 
	('Elfin'), 
	('Elio'), 
	('Englon'), 
	('Enranger'),
	('Enovate'), 
	('Esemka'), 
	('Etox'), 
	('Equus'), 
	('Everus'),
	('Faraday Future'), 
	('FAW'), 
	('Ferrari'), 
	('Fiat'), 
	('Fiat Professional'), 
	('Fisker'), 
	('Foday'), 
	('Force'), 
	('Ford'), 
	('Foton'), 
	('Fraser'),
	('GAC'), 
	('GAZ'), 
	('Geely'), 
	('GEM'), 
	('Genesis'), 
	('Geometry'), 
	('Gibbs'), 
	('Gillet'), 
	('Ginetta'), 
	('GMC'), 
	('Great Wall'), 
	('GTA'),
	('Haval'), 
	('Hawtai'), 
	('Hengchi'), 
	('Honda'), 
	('Hongqi'), 
	('Hozon'), 
	('Hulas Motors'), 
	('Hycan'), 
	('Hyundai'),
	('IKCO'), 
	('Infiniti'), 
	('Intermeccanica'), 
	('Isdera'), 
	('Isuzu'), 
	('Iveco Bus'),
	('JAC'), 
	('Jaguar'), 
	('Jeep'), 
	('Jetta'), 
	('Jinbei'), 
	('JMC'),
	('Kaipan'), 
	('Kantanka'),   
	('Karma'), 
	('Karry'), 
	('Kia'), 
	('Kiira'), 
	('Koenigsegg'), 
	('KTM'), 
	('Lada'), 
	('Lamborghini'), 
	('Lancia'), 
	('Land Rover'), 
	('Landwind'), 
	('Laraki'), 
	('Leapmotor'), 
	('LEVC'), 
	('Levdeo'), 
	('Lexus'), 
	('Li Auto'), 
	('Lifan'), 
	('Lightning'), 
	('Lincoln'), 
	('Lister'), 
	('Lotus'), 
	('Lucid'), 
	('Luxgen'), 
	('Lynk & Co'),
	('Mahindra'), 
	('Maple'), 
	('Maruti Suzuki'), 
	('Maserati'), 
	('Maxus'), 
	('Mazda'), 
	('McLaren'), 
	('Mega'), 
	('Mercedes-AMG'), 
	('Mercedes-Benz'), 
	('Mercedes-Maybach'), 
	('MG'), 
	('Micro'), 
	('Mini'), 
	('Mitsubishi'), 
	('Mitsuoka'), 
	('Morgan'), 
	('Neta'),
	('NEVS'), 
	('Nikola'), 
	('Nio'), 
	('Nismo'), 
	('Nissan'), 
	('Noble'), 
	('Opel'), 
	('Ora'), 
	('Pagani'), 
	('PAL-V'), 
	('Panoz'), 
	('Pars Khodro'), 
	('Perodua'), 
	('Peugeot'), 
	('Pininfarina'), 
	('Polaris'), 
	('Polestar'), 
	('Porsche'), 
	('Praga'), 
	('Proton'),
	('Qoros'), 
	('Quant'),
	('Radical'), 
	('Ranz'), 
	('Renault'), 
	('Renault Samsung'), 
	('Rimac'), 
	('Rinspeed'), 
	('Rivian'), 
	('Rezvani'), 
	('Roding'), 
	('Roewe'), 
	('Rolls-Royce'), 
	('Ronart'), 
	('Ronn'), 
	('Ruf'),
	('SAIPA'), 
	('Saker'), 
	('Saleen'), 
	('SEAT'), 
	('Sehol'), 
	('Seres'), 
	('Skyworth'), 
	('SIN'),     
	('SiTech'), 
	('Skoda'), 
	('Shelby'), 
	('Sono'), 
	('Smart'), 
	('Soueast'), 
	('Spyker'),  
	('SsangYong'), 
	('SSC'), 
	('Subaru'), 
	('Superformance'), 
	('Suzuki'),
	('Tata'), 
	('Tesla'), 
	('Thai Rung'), 
	('Tiger'), 
	('TOGG'), 
	('Toyota'),
	('Tramontana'),
	('Trion'),
	('Tushek&Spigel'),  
	('TVR'),
	('UAZ'), 
	('Ultima'), 
	('Uniti'), 
	('Vauxhall Motors'), 
	('Vega'), 
	('Vencer'), 
	('Venturi'), 
	('VGV'),
	('VinFast'), 
	('Volkswagen'), 
	('Volvo'), 
	('Voyah'), 
	('VUHL'),
	('W Motors'), 
	('Wallyscar'), 
	('WaterCar'), 
	('Weineck'),
	('Weltmeister'), 
	('Westfield'), 
	('Wey'), 
	('Wheego'), 
	('Wiesmann'), 
	('Wuling'),
	('XPeng'),
	('Yudo'),
	('Zamyad'), 
	('Zedriv'), 
	('Zeekr'), 
	('Zenos Cars'), 
	('Zenvo'), 
	('Zhidou'),
	('ZX')
GO
